name: Update Zenodo Deposition

on:
  workflow_dispatch:
    inputs:
      deposition_id:
        description: "Existing Zenodo Deposition ID"
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create new version
        id: newversion
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.ZENODO_TOKEN }}" \
            https://sandbox.zenodo.org/api/deposit/depositions/${{ github.event.inputs.deposition_id }}/actions/newversion)

          NEW_DRAFT_URL=$(echo $response | jq -r '.links.latest_draft')
          echo "NEW_DRAFT_URL=$NEW_DRAFT_URL"

          NEW_ID=$(basename $NEW_DRAFT_URL)  # ← URLの末尾がID
          echo "NEW_DEPOSITION_ID=$NEW_ID" >> $GITHUB_ENV

      - name: Update metadata for new version
        run: |
          curl -X PUT \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.ZENODO_TOKEN }}" \
            -d @metadata.json \
            https://sandbox.zenodo.org/api/deposit/depositions/${{ env.NEW_DEPOSITION_ID }} \
            > response.json

          echo "----- Zenodo API Response -----"
          cat response.json

          if [[ "$response" != "200" ]]; then
            echo "❌ Failed to update metadata"
            exit 1
          fi
      - name: Upload updated PDF
        run: |
          BUCKET_URL=$(curl -s -H "Authorization: Bearer ${{ secrets.ZENODO_TOKEN }}" \
            https://sandbox.zenodo.org/api/deposit/depositions/${{ env.NEW_DEPOSITION_ID }} \
            | jq -r .links.bucket)

          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.ZENODO_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @README.pdf \
            "$BUCKET_URL/README.pdf"

      - name: Publish updated deposition
        run: |
          response=$(curl -s -w "%{http_code}" -o publish_result.json \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.ZENODO_TOKEN }}" \
            https://sandbox.zenodo.org/api/deposit/depositions/${{ env.NEW_DEPOSITION_ID }}/actions/publish)

          echo "HTTP response code: $response"
          cat publish_result.json

          if [[ "$response" != "202" ]]; then
            echo "❌ Failed to publish updated deposition"
            exit 1
          fi